version: '3.1'

services:

  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    ports:
      - "5432:5432"
  redis:
    container_name: redis_container
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  cache:
    driver: local