# Generated by Django 4.1.1 on 2022-10-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosrv', '0002_alter_comment_options_alter_like_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ignored_users',
            field=models.ManyToManyField(blank=True, related_name='banned_users', to='videosrv.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='signed_users', to='videosrv.profile'),
        ),
    ]
