# Generated by Django 4.1.1 on 2022-12-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosrv', '0003_alter_profile_ignored_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
