# Generated by Django 4.1.1 on 2022-12-14 17:09

from django.db import migrations, models
import videosrv.models


class Migration(migrations.Migration):

    dependencies = [
        ('videosrv', '0004_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, upload_to=videosrv.models.uuid_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.FileField(blank=True, upload_to=videosrv.models.uuid_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload',
            field=models.FileField(upload_to=videosrv.models.uuid_path),
        ),
    ]
