# Generated by Django 4.1.1 on 2022-10-25 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_to',
        ),
        migrations.AddField(
            model_name='message',
            name='room_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_user_to', to='messenger.room'),
        ),
    ]
